spring:

  config:
    import:
      - optional:file:.env
  #    activate:
  #      on-profile: docker

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  datasource:
    master:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3307/project?serverTimezone=UTC&characterEncoding=UTF-8
      username: root
      password: 1234
    slave:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3308/project?serverTimezone=UTC&characterEncoding=UTF-8
      username: root
      password: 1234

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: "${baseUrl}/login/oauth2/code/kakao"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - profile_nickname
              - profile_image
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            #            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            #            token-uri: https://oauth2.googleapis.com/token사람
            #            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            #            user-name-attribute: sub
            scope:
              - email
              - profile

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id


jwt:
  secret-key: ${SECRET_KEY}

profiles:
  active: dev  # 개발 환경 프로필 활성화

server:
  ssl:
    enabled: false
  port: 8080
  tomcat:
    uri-encoding: UTF-8

  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true


logging:
  level:
    com.your.package: INFO  # 패키지명 수정 필요
    org.springframework.web: INFO
